language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=cacheanalysis --cover-inclusive -I visual_analysis cacheanalysis/tests

after_success:
  - codecov
